### ISSUE TITLE
Latest version fails to build with nixpkgs 24.11 using upstream receipt

### ISSUE THREAD

**Issue by blaggacao** [pimalaya/comodoro#18]
This doesn't look like a supported installation method, yet many people might expect it to work for practical reasons and to not introduce another nixpkgs pin into their environment.

Maybe there's a quick fix which would allow people to test out comodoro v1 as an overaly.

Nixpkgs 24.11 fails to build:

```
error: builder for '/nix/store/20hjkplc3l2sc1nhdyi5850sn0ysdbpa-comodoro-1.0.0-2024-11-29.drv' failed with exit code 101;
       last 25 log lines:
       >    Compiling clap_mangen v0.2.24
       >    Compiling time-lib v1.0.0 (https://github.com/pimalaya/core#3e294453)
       >    Compiling convert_case v0.6.0
       > error[E0609]: no field `cmd` on type `&HookConfig`
       >   --> src/preset/config.rs:49:33
       >    |
       > 49 |         if let Some(cmd) = self.cmd.as_ref() {
       >    |                                 ^^^ unknown field
       >
       > error[E0609]: no field `notify` on type `&HookConfig`
       >   --> src/preset/config.rs:59:36
       >    |
       > 59 |         if let Some(notify) = self.notify.as_ref() {
       >    |                                    ^^^^^^ unknown field
       >
       > error[E0433]: failed to resolve: use of undeclared type `Notification`
       >   --> src/preset/config.rs:60:25
       >    |
       > 60 |             let notif = Notification::new()
       >    |                         ^^^^^^^^^^^^ use of undeclared type `Notification`
       >
       > Some errors have detailed explanations: E0433, E0609.
       > For more information about an error, try `rustc --explain E0433`.
       > error: could not compile `comodoro` (lib) due to 3 previous errors
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/20hjkplc3l2sc1nhdyi5850sn0ysdbpa-comodoro-1.0.0-2024-11-29.drv'.
error: 1 dependencies of derivation '/nix/store/ind0607v094mp7i2zzxxh2mh47zm4yqp-comodoro.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/chhhb8yb7nlrxxg0i955yn39fcdvx2z4-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/az88l89w9qkkqdis21yn7kjjldlkyq54-home-manager-generation.drv' failed to build
```

```nix
{
  lib,
  rustPlatform,
  fetchFromGitHub,
  stdenv,
  installShellFiles,
  installShellCompletions ? stdenv.buildPlatform.canExecute stdenv.hostPlatform,
  installManPages ? stdenv.buildPlatform.canExecute stdenv.hostPlatform,
  withTcp ? true,
}:
rustPlatform.buildRustPackage rec {
  pname = "comodoro";
  version = "1.0.0-2024-11-29";

  src = fetchFromGitHub {
    owner = "soywod";
    repo = "comodoro";
    rev = "997de49cd70dcc488c5a1e16475e4ca8f03485f7";
    # rev = "v${version}";
    hash = "sha256-mp115TbUc226kDWDXtrbLO5sc/UqVFSNbqQBOnf7AFQ=";
  };

  useFetchCargoVendor = true;
  cargoHash = "sha256-NwEKPhZq6eLm1kgM6KLgDnXBIebMyi3bpIEoM/kjkho=";

  nativeBuildInputs = lib.optional (installManPages || installShellCompletions) installShellFiles;

  buildNoDefaultFeatures = true;
  buildFeatures = lib.optional withTcp "tcp";

  postInstall =
    lib.optionalString installManPages ''
      mkdir -p $out/man
      $out/bin/comodoro man $out/man
      installManPage $out/man/*
    ''
    + lib.optionalString installShellCompletions ''
      installShellCompletion --cmd comodoro \
        --bash <($out/bin/comodoro completion bash) \
        --fish <($out/bin/comodoro completion fish) \
        --zsh <($out/bin/comodoro completion zsh)
    '';

  meta = with lib; {
    description = "CLI to manage your time";
    homepage = "https://github.com/pimalaya/comodoro";
    changelog = "https://github.com/soywod/comodoro/blob/v${version}/CHANGELOG.md";
    license = licenses.mit;
    maintainers = with maintainers; [soywod];
    mainProgram = "comodoro";
  };
}
```

**Comment by blaggacao** [comment]
Looks like this is not a legit issue report: https://github.com/pimalaya/comodoro?tab=readme-ov-file#other-outdated-methods

**Comment by soywod** [comment]
Indeed I did not have time yet to take care of Comodoro CLI, it's in the pipeline. The nix derivation is supposed to work the same way as Himalaya or Neverest CLI.
